### ISSUE TITLE
Spark Sound (global)

### ISSUE THREAD

**Issue by Aeniema** [zealsprince/lc-malfunctions#11]
When spark sound enables, it becomes a global sound to player and gets stuck. No logs available.

**Comment by zealsprince** [comment]
Should have been fixed as part of [03b75fc](https://github.com/zealsprince/lc-malfunctions/commit/03b75fce6a7182610cf409f5b82bb04bbe2d4776) with version 1.4.1. Let me know which malfunction causes this in case it appears again!
