### ISSUE TITLE
Make a post on the LC Modding discord

### ISSUE THREAD

**Issue by Easyidle123** [zealsprince/lc-malfunctions#14]
I know of several people who'd love to discuss / give feedback on this mod, but the github issues are too intimidating / not the right medium for their communication. I think it'd be great if you joined the [Lethal Company Modding Discord](https://discord.gg/XeyYqRdRGC) and made a [Mod Releases](https://discord.com/channels/1168655651455639582/1169056298856362105) post!

**Comment by zealsprince** [comment]
Sounds good! I'll do that this weekend!

**Comment by zealsprince** [comment]
Done! Thanks for the suggestion!
