### ISSUE TITLE
[bug] After the ship departs, it enters a soft lock state.

### ISSUE THREAD

**Issue by ghost** [zealsprince/lc-malfunctions#19]
There is a bug where if the player orbits after not receiving a malfunction warning, the lever will no longer work.

**Comment by zealsprince** [comment]
Could you post your mod list as well as the error here?

**Comment by ghost** [comment]
mod list :

BepInExPack v5.4.2100 by BepInEx
MaskedEnemyOverhaul v3.1.2 by HomelessGinger
Skinwalkers v4.0.3 by RugbugRedfern
Runtime_Netcode_Patcher v0.2.5 by Ozone
More_Emotes v1.3.3 by Sligili
MoreMoneyStart v2.1.0 by 299792458
HDLethalCompany v1.5.6 by Sligili
LethalCompany_InputUtils v0.7.3 by Rune580
FlashlightToggle v1.5.0 by Renegades
ShipLoot v1.1.0 by tinyhoot
HotbarPlus v1.5.11 by FlipMods
WalkieUse v1.5.0 by Renegades
HidePlayerNames v1.0.2 by Monkeytype
Mimics v2.4.1 by x753
MimicKoreanPatch v1.0.3 by Piggy
Touchscreen v1.1.0 by TheDeadSnake
HookGenPatcher v0.0.5 by Evaisa
TerminalApi v1.5.2 by NotAtomicBomb
LethalLib v0.15.0 by Evaisa
FixPluginTypesSerialization v1.1.1 by Evaisa
CSync v4.1.0 by Sigurd
FacilityMeltdown v2.4.8 by loaforc
Malfunctions v1.8.2 by zealsprince
OdinSerializer v2022.11.9 by Lordfirespeed
LethalNetworkAPI v2.1.6 by xilophor

error :

[Error  : Unity Log] NullReferenceException
Stack trace:
Malfunctions.Patches.StartOfRoundPatches.RestoreAfterMalfunctions () (at <8442d1f43a9f427f8fb0532dd7f97209>:IL_0054)
Malfunctions.Patches.StartOfRoundPatches.RollMalfunctions (StartOfRound instance) (at <8442d1f43a9f427f8fb0532dd7f97209>:IL_0000)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::ReviveDeadPlayers>(StartOfRound)
StartOfRound+<EndOfGame>d260.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_030C)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by ghost** [comment]
P.s
This probably happens when you save the game and then host it again.

**Comment by zealsprince** [comment]
This should have been fixed as of the latest version!
