### ISSUE TITLE
Weather stuck on all maps after navigational malfunction happened

### ISSUE THREAD

**Issue by Hardeh** [zealsprince/lc-malfunctions#2]
So navigational malfunction happened, sending me to Rend
Weather on Rend was foggy
After taking off i have foggy weather everywhere else, including the company building. Moreso, foggy weather applied on top of real weather, so it's flooded + foggy, eclipsed + foggy, etc.

**Comment by Hardeh** [comment]
Double weather may have happened because i use https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaks/
But it still maybe worth looking into.

**Comment by zealsprince** [comment]
Looking into this! I had it happen once but wasn't able to reproduce since. Will try some more to figure out what's going on.

**Comment by dolanske** [comment]
Is it fixed yet @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince @zealsprince

**Comment by kilmanio** [comment]
Go to bed, @dolanske

**Comment by dolanske** [comment]
Why are you pinging me I am busy

**Comment by zealsprince** [comment]
Possibly fixed as part of 1.2.1: The level change malfunction now happens after the game goes through its EndOfRound yields that reset the weather - need to do more testing to confirm this works but so far I haven't encountered it.

Let me know if it's still presents itself!
