### ISSUE TITLE
[Error] In console

### ISSUE THREAD

**Issue by MathiusXII** [zealsprince/lc-malfunctions#23]
[Error  :Malfunctions] Failed to find door panel screen from previous reference.

**Comment by zealsprince** [comment]
Any further information around when this happened? It can happen but shouldn't break the game. Maybe I should downgrade this to a warning rather than an error log.

**Comment by MathiusXII** [comment]
It was in my console when my friend was hosting the modpack, but not there in singleplayer.

**Comment by zealsprince** [comment]
Modified as of https://github.com/zealsprince/lc-malfunctions/commit/e3433f020e4dfad749eb546582d9ac4ab0137d6f
