### ISSUE TITLE
new malfunction idea

### ISSUE THREAD

**Issue by willoheajaunka** [zealsprince/lc-malfunctions#3]
"Hydraulic malfunction" meaning: "Door malfunction".
The door can open and close by-itself. like 16 seconds closed, then 6 seconds opened. the number being random each per landing. but past 4 PM. it will re-roll like a "Computer and Door Malfunction". as if the computer is now itself is confused if the door is open or closed. during this re-roll. it will be closed longer and opened shorter. like minus the current value. by a number between 3 to 6 seconds. this will minus the 6 second by this piked number. if it happens to go below 3 seconds length opened. just set it to 3 (so it's fair). and then add a random amount to the length closed. like an extra 5 to 12 seconds. Why i think this pre-set thing would be better, is so its consistent. it's not like every second it has a chance to open or close 50/50. that would be too random. but that could be a 2nd worse, rarer version of this. like a "Computer to door malfunction". as if it gotten smashed accidently or some water got into it.

**Comment by zealsprince** [comment]
I implemented something like this in the latest version 1.3.0. Go give it a try!
