### ISSUE TITLE
It's not clear what the problem is

### ISSUE THREAD

**Issue by Paradox75831004** [zealsprince/lc-malfunctions#7]
018d8550-2105-518c-cb0a-27ed476ad293

![image](https://github.com/zealsprince/lc-malfunctions/assets/72872478/58179dd7-d86d-4bc9-b26b-4f1a891e7a3a)

**Comment by Paradox75831004** [comment]
[LogOutput.log](https://github.com/zealsprince/lc-malfunctions/files/14201361/LogOutput.log)

**Comment by zealsprince** [comment]
You're playing on an old version of the mod (1.1.1). I'm not sure if your issue still exists with the latest version. I would recommend updating it.

**Comment by zealsprince** [comment]
I realized this was a problem I introduced in 1.3.0. It's been fixed in 1.4.0 the latest version! Sorry about that!
