### ISSUE TITLE
Some kind of mistake, there is no dismissal, even manually

### ISSUE THREAD

**Issue by Paradox75831004** [zealsprince/lc-malfunctions#8]
I tried to quit manually on the last day before submitting the quota through the "Eject" command - it did not work. He flew into the company building, died - the ship flew away - the dismissal did not occur
018d874f-a42e-74a7-0a5c-b8f837f78875
![image](https://github.com/zealsprince/lc-malfunctions/assets/72872478/212d7110-49ae-43ad-93e5-cd67a0d25efb)
[LogOutput.log](https://github.com/zealsprince/lc-malfunctions/files/14204827/LogOutput.log)

**Comment by zealsprince** [comment]
From reading those logs; it doesn't mention my mod at all? I don't know the `MoreShipUpgrades` mod but you should message its author instead.
